Add db/ to Jest ignore patterns
Invalid JSON in the database causes Jest to fail:

```
> hound@1.0.0 test
> jest

Error: Cannot parse [...]/go/src/github.com/hound-search/hound/db/idx-134619d3dcb11318/raw/package.json as JSON: Unexpected token  in JSON at position 0
```